language: node_js
sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  matrix:
  - NODE_VER=8

matrix:
  fast_finish: true

before_install:
  - nvm install $NODE_VER
  - npm install -g npm@5.4.2
  - npm install -g greenkeeper-lockfile@1
  - node -v && npm -v

install:
  - npm install

before_script: greenkeeper-lockfile-update

script:
  - npm run build
  - npm test
  - npm run manifest
  - cat ./src/manifest.ts

after_script: greenkeeper-lockfile-upload
