language: node_js
sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  matrix:
  - NODE_VER=5 FULL_VALIDATE=true
  - NODE_VER=6 FULL_VALIDATE=false
  - NODE_VER=7 FULL_VALIDATE=false
  - NODE_VER=8 FULL_VALIDATE=true

matrix:
  fast_finish: true

before_install:
  - nvm install $NODE_VER
  - npm install -g npm@5.6.0
  - npm install -g greenkeeper-lockfile@1
  - node -v && npm -v

install:
  - npm install

before_script: greenkeeper-lockfile-update

script:
  - npm run build
  - npm test
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run manifest:generate && npm run manifest:validate && cat ./src/manifest.ts; fi

after_script: greenkeeper-lockfile-upload
