environment:
  matrix:
  # node.js
    - nodejs_version: "10"
    - nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g npm@latest
  - node -v && npm -v
  - npm install

build_script:
  - npm run build

test_script:
  - npm test
  - npm run manifest:generate
  - npm run manifest:validate
  - cd src && type manifest.ts

version: "{build}"