version: 2
jobs:
  build:
    working_directory: ~/hunspell-dict-downloader
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Checking Versions
          command: |
            sudo npm install -g npm@latest
            node --version && npm --version
      - run:
          name: prepare
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: |
            npm test
            bash <(curl -s https://codecov.io/bash)